### ISSUE TITLE
Bonus

### ISSUE THREAD

**Issue by sebacruzd** [ofvera/Tarea7#36]
```
while True:
    self.probar_bonus()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'spam' is not defined
```

**Comment by ofvera** [comment]
**Encontramos la siguiente respuesta:** 
TL;DR input function in Python 2.7, evaluates whatever your enter, as a Python expression. If you simply want to read strings, then use raw_input function in Python 2.7, which will not evaluate...

[Link: https://stackoverflow.com/questions/21122540/input-error-nameerror-name-is-not-defined/21122817]
